### ISSUE TITLE
Intermittent "Download should begin but no data connection is available" errors

### ISSUE THREAD

**Issue by wavded** [patrickjuchli/basic-ftp#106]
**Describe the bug**
Seems like there is a race condition when establishing the `config.ftp.dataSocket` as I get intermittent errors. E.g. sometimes a `.list` call works, sometimes it errors with the message below. Running latest release (v4.5.0)

**Example code**
```
  const client = new Client()
  try {
    await client.access({
     host: "---"
     user: "---"
     password: "---"
   })
    client.ftp.verbose = true
    const files = await client.list()
    console.log(files)
  } finally {
    client.close()
  }
```

**Console output**

```
Trying to find optimal transfer strategy...
> EPSV
< 500 'EPSV': command not understood
> PASV
< 227 Entering Passive Mode (12,31,157,148,233,129)
Optimal transfer strategy found.
> MLSD
< 500 'MLSD': command not understood
> PASV
< 227 Entering Passive Mode (12,31,157,148,226,28)
> LIST -a
< 125 Data connection already open; Transfer starting.
Error: Download should begin but no data connection is available.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Download should begin but no data connection is available.]
    at: <anonymous> (/Users/---/Projects/---/node_modules/blue-tape/blue-tape.js:20:20)
    stack: |-
      Error: Download should begin but no data connection is available.
          at Object.responseHandler (/Users/wavded/Projects/pqs/node_modules/basic-ftp/dist/transfer.js:263:40)
          at FTPContext._passToHandler (/Users/wavded/Projects/pqs/node_modules/basic-ftp/dist/FtpContext.js:287:24)
          at FTPContext._onControlSocketData (/Users/wavded/Projects/pqs/node_modules/basic-ftp/dist/FtpContext.js:277:18)
          at Socket.<anonymous> (/Users/wavded/Projects/pqs/node_modules/basic-ftp/dist/FtpContext.js:121:44)
          at Socket.emit (events.js:210:5)
          at Socket.EventEmitter.emit (domain.js:476:20)
          at addChunk (_stream_readable.js:308:12)
          at readableAddChunk (_stream_readable.js:285:13)
          at Socket.Readable.push (_stream_readable.js:223:10)
          at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
  ...
```

**Which version of Node.js are you using?**
Tested on Node 10 and 12.

**Comment by wavded** [comment]
I tested previous versions of this library to see when this behavior started happening and it appears to have been introduced in v4.3.2. I am not seeing this issue with v4.3.1 or earlier.

**Comment by patrickjuchli** [comment]
I've published a new version 4.5.1 where I remove a check that might be too early. I'm not sure yet what's going on here but at least we should get a more interesting error message if the issue persists.

**Comment by wavded** [comment]
@patrickjuchli so far so good in my testing, thanks for quick turnaround!

**Comment by patrickjuchli** [comment]
Hm, apparently `remoteAddress` of a socket is resolved much later than I'd expect.
