### ISSUE TITLE
ENOTFOUND on Ubuntu

### ISSUE THREAD

**Issue by schinkowitch** [patrickjuchli/basic-ftp#11]
I'm getting the following error when using version 2.12.0 (works ok with 2.11.0):
 
Error: getaddrinfo ENOTFOUND ftps.vianett.no ftps.vianett.no:21
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'ftps.vianett.no',
     host: 'ftps.vianett.no',
     port: 21

`
const ftp = require('basic-ftp');

connectToFTP()
    .then(function () {
        console.log('OK');
        process.exit(0);
    })
    .catch(function (err) {
        console.error(err);
        process.exit(1);
    });

async function connectToFTP (params) {
    const client = new ftp.Client(10000);

    client.ftp.verbose = true;
    client.ftp.log = function (message) {
        console.log(message);
    };

    try {
        await client.connect('ftps.vianett.no', 21);
        await client.useTLS();
    } catch (err) {
        console.error(err);
        throw err;
    } finally {
        client.close();
        console.log('done');
    }
}
`
running on:
Linux ip-172-31-25-241 4.4.0-1057-aws #66-Ubuntu SMP Thu May 3 12:49:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by patrickjuchli** [comment]
Node can’t resolve the host name. This might be related to IPv6 being an issue on the Ubuntu box. Does it work if you use `client.ftp.ipFamily = 4` before connecting to the server? Which version of Node are you using?

**Comment by schinkowitch** [comment]
adding `client.ftp.ipFamily = 4` before connecting fixes the problem.
Node version: v8.11.2

**Comment by patrickjuchli** [comment]
Okay, I'll investigate this a bit further, let's keep the issue open.

I have removed the hostname you provided in the issue. It did help me a bit but be careful with that.
