### ISSUE TITLE
Error: Timeout (data socket)

### ISSUE THREAD

**Issue by jzonta** [patrickjuchli/basic-ftp#114]
**Describe the bug**
The error happens when I use the command `await client.downloadToDir('./downloads/', './');`

Some files are downloaded, but at some point stop with the following message.

```
Downloading from undefined:undefined (No encryption)
Error: Timeout (data socket)
    at Socket.socket.once (/home/joao-zonta/projetos/inttraworks/node_modules/basic-ftp/dist/FtpContext.js:310:58)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

When I use another ftp program the error does not occur.

**Which version of Node.js are you using?**
v10.15.2

**Comment by patrickjuchli** [comment]
This `undefined:undefined` is similar to #107... the problem disappeared when updating Node. Could you try updating?

**Comment by jzonta** [comment]
I upgraded the node, but the problem continued, so I checked it out:
The problem was with my directory.
If I browse to the folder and then download it, it doesn't work:
```
await client.cd ('folder / subfolder')
await client.downloadToDir ('./ downloads /', './')
```

But if I do like this:
`await client.downloadToDir ('./ downloads /', './folder/subfolder')`

It works correctly.

Thank you for your help
