### ISSUE TITLE
Error: Client is closed

### ISSUE THREAD

**Issue by skills-surendra** [patrickjuchli/basic-ftp#132]
**Describe the bug**
I am getting error after 1 minute :
Error: Client is closed
    at /var/www/html/project/nodejs/node_modules/basic-ftp/dist/FtpContext.js:220:29
    at new Promise (<anonymous>)
    at FTPContext.handle (/var/www/html/project/nodejs/node_modules/basic-ftp/dist/FtpContext.js:200:16)
    at FTPContext.request (/var/www/html/project/nodejs/node_modules/basic-ftp/dist/FtpContext.js:177:21)
I am using this connection in for loop to get the files list and  download files.
My Code is : 
const client = new ftp.Client(0)
        client.ftp.verbose = true
        

        try {
            await client.access({
                host: "xx.xx.xx.xxxx",
                user: "aaaaaa",
                password: "*******",
                secure: false
            });
            return client;
            
        }
        catch(err) {
            console.log(err)
        }
**Which version of Node.js are you using?**
 Node => 12.14.1

**Comment by patrickjuchli** [comment]
This is not enough information to help you. In the stack trace further below you see the reason why your client is closed.

**Comment by patrickjuchli** [comment]
Closing due to inactivity. Feel free to reopen if there is news.
