### ISSUE TITLE
Error: Can't parse response to 'EPSV': 227 Entering Passive Mode

### ISSUE THREAD

**Issue by nitinai-ms** [patrickjuchli/basic-ftp#135]
**Describe the bug**
I am trying to connect to a ftp server. 
The connection is ok, I can change the directory by using "client.cd()"
But when it hits client.list(), it prints out error logs (please see below)

However, It works fine with FileZilla.

Do you encounter the same issue when using another FTP server?
No

**Example code**
```javascript
const ftp = require("basic-ftp")
 
example()
 
async function example() {
    const client = new ftp.Client()
    client.ftp.verbose = true
    try {
        await client.access({
            host: "##",
            user: "##",
            password: "##",
            secure: false
        })
        console.log(await client.list()) //<--- Error at this line
    }
    catch(err) {
        console.log(err)
    }
    client.close()
}
```

**Console output**
```
< 331 Password required for ##
> PASS ##
< 230-Welcome to ##
230 Login OK
> TYPE I
< 200 Type set to I.
> STRU F
< 200 Structure set to F.
> OPTS UTF8 ON
< 502 This function is disabled
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 504 Invalid command parameter
Trying to find optimal transfer strategy...
> EPSV
< 227 Entering Passive Mode (91,220,214,97,201,133)
Error: Can't parse response to 'EPSV': 227 Entering Passive Mode (91,220,214,97,201,133)
    at parseEpsvResponse (/project-dir/node_modules/basic-ftp/dist/transfer.js:31:15)
    at enterPassiveModeIPv6 (/project-dir/node_modules/basic-ftp/dist/transfer.js:11:18)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Client.prepareTransfer (/project-dir/node_modules/basic-ftp/dist/Client.js:656:33)
    at Client.list (/project-dir/node_modules/basic-ftp/dist/Client.js:451:13)
    at example (/project-dir/.webpack-projectapi/service/handlers/jobRunner/webpack:/src/methods/jobRunner/utils/ftpParser.js:24:17)
```

**Which version of Node.js are you using?**
v12.15.0

**Comment by nitinai-ms** [comment]
Sorry, I may need to close this down.

I found the solution in here https://github.com/patrickjuchli/basic-ftp/issues/133

**Comment by patrickjuchli** [comment]
The response to the EPSV command is indeed not correct, though. Which FTP server is that?

```
> EPSV
< 227 Entering Passive Mode (91,220,214,97,201,133)
```

**Comment by nitinai-ms** [comment]
> The response to the EPSV command is indeed not correct, though. Which FTP server is that?
> 
> ```
> > EPSV
> < 227 Entering Passive Mode (91,220,214,97,201,133)
> ```

Sorry I can't give you more details about FTP server.
Just using one which provided by a customer.

Anyway, It works now with this:
```javascript
const ftp = require("basic-ftp")

client.prepareTransfer = ftp.enterPassiveModeIPv4
```
