### ISSUE TITLE
Hostname/IP does not match

### ISSUE THREAD

**Issue by nelsonkd** [patrickjuchli/basic-ftp#158]
Gettting the following error:

```
  Connected to 107.21.193.164:21 (No encryption)
  < 220 Service ready for new user.
  > AUTH TLS
  < 234 Command AUTH okay; starting TLS connection.
  Control socket is using: TLSv1.2
  Login security: TLSv1.2
 > USER 93b695d30ac62c79743b7a99ee0884
  < 331 User name okay, need password for 93b695d30ac62c79743b7a99ee0884.
  > PASS ###
  < 230 User logged in, proceed.
  > TYPE I
  < 200 Command TYPE okay.
  > STRU F
  < 200 Command STRU okay.
  > OPTS UTF8 ON
  < 200 Command OPTS okay.
  > OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
  < 200 Command OPTS okay.
  > PBSZ 0
  < 200 Command PBSZ okay.
  > PROT P
  < 200 Command PROT okay.
  [1596575020856] INFO  (###): UPLOADING ...
  Trying to find optimal transfer strategy...
  > EPSV
  < 229 Entering Passive Mode (|||8193|)
  Optimal transfer strategy found.
  > STOR 2020-08-04.csv
  < 150 File status okay; about to open data connection.
  Uploading to 107.21.193.164:8193 (TLSv1.3)
  [1596575021542] ERROR (###): Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.sftptogo.com (data socket)
      Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.sftptogo.com
          at Object.checkServerIdentity (tls.js:288:12)
          at TLSSocket.onConnectSecure (_tls_wrap.js:1484:27)
          at TLSSocket.emit (events.js:310:20)
          at TLSSocket._finishInit (_tls_wrap.js:917:8)
          at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12)
```

CODE:
```
async function uploadToFtp(dir, fileName) {
    let client =  new ftp.Client();
    client.ftp.verbose = true;
    
    try {
        await client.access({
            host: process.env.FTP_HOST,
            user: process.env.FTP_USER,
            password: process.env.FTP_PASSWORD,
            secure: true
        });

        logger.info(`UPLOADING ...`);
        await client.uploadFrom(`./${fileName}`, fileName );

    } catch (error) {
        logger.error(error);
    }
}
```

Using SFTP To Go on Heroku as my FTP. I have also tried another ftp server and getting similar results.  Not sure if I am doing something wrong or if the hard coding of localhost is over-riding my host - don't think so, but not sure.

**Comment by patrickjuchli** [comment]
Actual hostname doesn't match the one mentioned in the certificate. This is not a library issue, for further guidance please use Stackoverflow or similar. Error message does mention localhost, so there is something there,

**Comment by nelsonkd** [comment]
What what host? I am not calling from localhost and the default in the API is localhost, yet I am providing a host value. So where is it getting localhost from?
