### ISSUE TITLE
TypeError: source.once is not a function, when uploading stream from zip provide by unzipper.

### ISSUE THREAD

**Issue by smroutes** [patrickjuchli/basic-ftp#161]
I was trying to upload a zip content with streaming, provide by the unzipper library. First I try to create the directory then try to change the current directory before push each file in a loop. I checked that object is readable stream as mention here https://github.com/patrickjuchli/basic-ftp/issues/66 . But still getting this use TypeError: source.once is not a function.

```js
const directory = await unzipper.Open.file(path.join(filePath, `file.zip`));
let dirs = directory.files.filter(el => el.type === 'Directory').map(el => el.path.split('/').splice(1).join('/')).filter(el => el !== '');

// Working
for await (let dir of dirs) {
    await client.ensureDir(`/${dir}`);
    await client.clearWorkingDir();
}

let files = directory.files.filter(el => el.type === 'File');
for await (const entry of files) {
    console.log(typeof entry.read != 'function'); // return true;
    
    let fileArray = entry.path.split("/");
    let fileName = fileArray.pop();
    let dir = fileArray.splice(1).join("/");
    await client.cd(`/${dir}`);
    await client.uploadFrom(entry, fileName);
}
```

```bash
true                                                                 
> CWD /                                         
< 250 OK. Current directory is /                
                                                                     
Error : TypeError: source.once is not a function    
at Client._uploadFromStream (<project>\node_modules\basic-ftp\dist\Client.js:378:16)
at Client._uploadWithCommand (<project>\node_modules\basic-ftp\dist\Client.js:353:21)
at Client.uploadFrom (<project>\node_modules\basic-ftp\dist\Client.js:334:21)
at Object.deploy (<project>\batch\project\app.js:192:30)
at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

λ node --version
v12.14.1

**Comment by smroutes** [comment]
await client.uploadFrom(entry.stream(), fileName);
Fixed
