### ISSUE TITLE
uploadFromDir throws error with nested folders

### ISSUE THREAD

**Issue by hcorta** [patrickjuchli/basic-ftp#169]
Hi! First of all thanks for this great library.

**Describe the bug**
I'm trying to upload the whole content of a folder by using the uploadFromDir method. The content includes some files + some subfolders with more content. 2 folders, all files are lightweight txt files. The first level is being uploaded as expected but whenever it gets to the second levels (nested folders), it throws an error. By running some tests I've found that if the subfolders are empty the process is completed successfully. 

**Console output**
```
const err = code >= 400 ? new FTPError(response) : undefined;
                                      ^
FTPError: 425 Can't open data connection.
    at FTPContext._onControlSocketData (/Users/nicepeople/repos/youbora-cli/node_modules/basic-ftp/dist/FtpContext.js:282:39)
    at TLSSocket.<anonymous> (/Users/nicepeople/repos/youbora-cli/node_modules/basic-ftp/dist/FtpContext.js:123:44)
    at TLSSocket.emit (node:events:329:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:275:11)
    at TLSSocket.Readable.push (node:internal/streams/readable:218:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:192:23) {
  code: 425
}
```

**Which version of Node.js are you using?**
v15.2.1

Thanks in advance

**Comment by patrickjuchli** [comment]
That's your FTP server telling you that it can't open the connections required to transfer the data. Do you know more about this server? Are you connecting to it locally? Not sure about the theory around nested folders, how about if the base folder contains a lot of files?

**Comment by hcorta** [comment]
Hi @ patrickjuchli!
wow, thanks for the quick answer.

Basically, if I try this, it works like a charm (the empty subFolder is properly created) :

```
exampleDir/
---file1.txt
---file2.txt
---subFolder/

...
client.uploadFromDir(exampleDir)
```

But whenever I include some file within the subFolder, it throws the below mentioned error:
```
exampleDir/
---file1.txt
---file2.txt
---subFolder/
------file3.txt

...
client.uploadFromDir(exampleDir)
```


Here are the last steps of the process in the uploading process: 
```
(***)

> EPSV
< 229 Entering Passive Mode (|||8089|)

> STOR file2.text
< 150 File status okay; about to open data connection.

Uploading to 91.126.149.228:8089 (TLSv1.3)
< 226 Transfer complete.

> MKD subFolder
< 257 "/subFolder" created.

> CWD subFolder
< 250 Directory changed to /subFolder

> EPSV
< 229 Entering Passive Mode (|||13881|)

> STOR file3.txt
< 150 File status okay; about to open data connection.

Uploading to 91.126.149.228:13881 (TLSv1.3)
< 425 Can't open data connection.

> CWD /
< 250 Directory changed to /

FTPError: 425 Can't open data connection.
    at FTPContext._onControlSocketData (/Users/nicepeople/repos/youbora-cli/node_modules/basic-ftp/dist/FtpContext.js:282:39)
    at TLSSocket.<anonymous> (/Users/nicepeople/repos/youbora-cli/node_modules/basic-ftp/dist/FtpContext.js:123:44)
    at TLSSocket.emit (node:events:329:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:275:11)
    at TLSSocket.Readable.push (node:internal/streams/readable:218:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:192:23) {
  code: 425
}
```

***
Am I doing something wrong?. 
Maybe is there any config in my server that can be caused this problem?

Thanks in advanced.

**Comment by patrickjuchli** [comment]
I don't know what's going on here, sorry. `425 Can't open data connection` is an error message coming from the server, and I don't see any reason from the logs why it would send that. I can only suggest to try another client or server at this point, sorry.

**Comment by patrickjuchli** [comment]
Closing this due to inactivity, reopen if there is new information.
