### ISSUE TITLE
Error: None of the available transfer modes work.

### ISSUE THREAD

**Issue by amiroff157** [patrickjuchli/basic-ftp#199]
**Describe the bug**

I'm receiving this error while trying to upload files to a remote folder. The connection runs as a gulp.js task and it works fine on a local machine (Windows) with the same Node.js version installed but when running via a Travis CI environment, Node.js seems to have difficulties keeping the connection open to transmit the files.

**Example code**
```
gulp.task('deploy', async (done) => {

  const config = {
    user: $$$,
    password: $$$,
    host: 'ftp.mydomain.com',
    localBuildDir: __dirname + '/build',
    remoteBuildDir: '/mywebsite/',
  };

  const client = new ftp.Client();
  client.ftp.verbose = true;
  try {
    await client.access({
      host: config.host,
      user: config.user,
      password: config.password,
      secure: false,
    });
    console.log(await client.list());
    await client.ensureDir(config.remoteBuildDir);
    await client.uploadFromDir(config.localBuildDir);
  } catch (err) {
    console.log('FTP error: ', err);
  }
  client.close();

  done();
});
```

**Console output**
```
Connected to my_ip_address:21 (No encryption)
< 220 ipage FTP Server Ready
Login security: No encryption
> USER gulp-ftp
< 331 Password required for gulp-ftp
> PASS ###
< 230 User gulp-ftp logged in
> FEAT
< 211-Features:
 CLNT
 EPRT
 EPSV
 HOST
 LANG en-US*
 MDTM
 MFF modify;UNIX.group;UNIX.mode;
 MFMT
 MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
 REST STREAM
 SITE MKDIR
 SITE RMDIR
 SITE SYMLINK
 SITE UTIME
 SIZE
<  TVFS
 UTF8
211 End
> TYPE I
< 200 Type set to I
> STRU F
< 200 Structure set to F
> OPTS UTF8 ON
< 200 UTF8 set to on
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200 MLST OPTS type;size;modify;unique;UNIX.mode;UNIX.owner;UNIX.group;UNIX.ownername;UNIX.groupname;
Trying to find optimal transfer mode...
> EPSV
< 229 Entering Extended Passive Mode (|||4500|)
Transfer mode failed: "Can't open data connection in passive mode: connect ECONNREFUSED my_ip_address:4500", will try next.
> PASV
< 227 Entering Passive Mode (my_ip_address,46,6)
Transfer mode failed: "Can't open data connection in passive mode: connect ECONNREFUSED my_ip_address:11782", will try next.
FTP error:  Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/travis/build/my-website/node_modules/basic-ftp/dist/Client.js:701:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.list (/home/travis/build/my-website/node_modules/basic-ftp/dist/Client.js:485:13)
    at async /home/travis/build/my-website/gulpfile.js:191:17
```

**Which version of Node.js are you using?**
`Node v14.17.2`

**Additional context**
the upload works on my local machine (Windows) with the same version installed. I get this success message after upload:
```
Uploading to my_ip_address:15832 (No encryption)
< 226 Transfer complete

> CDUP
< 250 CDUP command successful
```

**Comment by amiroff157** [comment]
looks like a CI issue... I ended up using the GitHub actions feature to build and deploy instead and the FTP deploy there works!
