### ISSUE TITLE
451-Transfer aborted with small file

### ISSUE THREAD

**Issue by MathiasDrapier** [patrickjuchli/basic-ftp#227]
I have a website where I can upload files that the server then sends to an ftp server. I use express nodejs and for the ftp library I use basic-ftp.

Here is my code :

`
router.post('/postUpdate', async function(req, res, next) {
    let target = req.body.target
    let v1 = req.body.v1
    let v2 = req.body.v2
    let v3 = req.body.v3
    let version = v1 + "." + v2 + "." + v3
    let changelog = req.body.changelog
    let path = "/"

    upload(req,res, async function (err) {
        try {
            if (!req.files) {
                return res.status(400).send('No files were uploaded.');
            } else {
                let file = req.files.file;
                file.mv("/usr/src/app/uploads/"+file.name).then( async function () {
                    path = "/test/"+file.name
                    const client = new ftp.Client()
                    try {
                        const secureOptions = {
                            rejectUnauthorized: false
                        }
                        await client.access({
                            host: config.ftpHost,
                            user: config.ftpUser,
                            password: config.ftpPassword,
                            secure: true,
                            secureOptions: secureOptions
                        })
                        await client.ensureDir("/test")
                        await client.uploadFrom(fs.createReadStream("/usr/src/app/uploads/" + file.name), path)
                        await client.close()
                    } catch (err) {
                        console.log(err)
                    }
                })
            }
        } catch (e) {
            console.log(e)
            res.status(500).send(e);
        }

    })
})
`

It works fine, but when I try with a small file: 20Ko I get an error from the basic-ftp library :

`
FTPError: 451-Transfer aborted
451 0.000 seconds (measured here), 122.70 Mbytes per second
    at FTPContext._onControlSocketData (/usr/src/app/node_modules/basic-ftp/dist/FtpContext.js:282:39)
    at TLSSocket.<anonymous> (/usr/src/app/node_modules/basic-ftp/dist/FtpContext.js:123:44)
    at TLSSocket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:284:11)
    at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 451
}
`

However I observe that the file is indeed uploaded on my ftp server and it is complete and not corrupted

**Comment by devkaH** [comment]
Is this issue always exists? because we also we get this error and we dont' find a solution.
Please if you resolve this issue, share it with us.
Thanks

**Comment by patrickjuchli** [comment]
This error (451 Transfer aborted) is being reported by your FTP server, it doesn't originate from `basic-ftp`.

I'm having a hard time reproducing this. Also, in your code, mixing `async/await` with `.then()` makes the code a bit hard to read. Did you try rewriting your code using only one of the approaches?

**Comment by patrickjuchli** [comment]
Closing due to inactivity. Do reopen if there is new information.
