### ISSUE TITLE
"There is still a task running" should provide more information

### ISSUE THREAD

**Issue by broofa** [patrickjuchli/basic-ftp#36]
It would be nice if this message indicated which task was still running, to aid in debugging.  E.g.:

    `download()` task is still running, ... (etc)"

**Comment by patrickjuchli** [comment]
Let's see how far we get when we use `Error` with stack traces everywhere as suggested in #37.

**Comment by patrickjuchli** [comment]
With fc5d640ca67ef42f77afc5c9b1c7a2254d197ce7, the client closes at least with a stack trace which should be helpful in debugging as it shows the responsible line.

Showing the type of operation is nice but doesn't strike me as necessary. What if you have several places where you download? A lot of the time you'll also see `send` for example.

**Comment by patrickjuchli** [comment]
What is more concerning is that the client doesn't exit nicely after this. And this is related to all other currently open topics on error handling.

**Comment by broofa** [comment]
I disagree.  The responsible line is the line that created the currently running task.  Heck, that's what the error message is referring to by "running task", right?  And that has a completely different stack then the one the caller will see in fc5d640.

In fact... the right thing to do here would probably be to capture the stack at the time a task is created, so that it can be surfaced here.  I.e in 
e8e7552, do something like `handler._trace = Error(command)`, instead of `handler._command = command`.  Then when this issue surfaces, just update the `_trace.message` and reject with that error, instead?  (I'm not actually sure that's a good idea since it would hide where the error is actually being thrown from but... you get the idea.)

Let me know if you want me to take a pass at this and I'll update my PR, otherwise... close this out I under protest, I guess? ;-)

**Comment by broofa** [comment]
> provide an Error subclass than can hold another Error

I actually don't like subclasses that hold important information in custom properties.   Such information tends to get dropped on the floor when you run those errors through error-handling services (e.g. bugsnag) or, heck, just `console.log`.

Maybe just start by appending it to the error stack, thusly ...

```
const err = new Error('There is still a task running...');
err.stack += `Currently running task created at:\n${handler._trace.stack}`;
this._closeWithError(err);
```

**Comment by patrickjuchli** [comment]
Exception looks like this right now:

```
Error: Client has been closed: User launched a task while another one is still running. Forgot to use 'await' or '.then()'?
    at Promise (/Users/patrick/Documents/Projects/basic-ftp/lib/FtpContext.js:286:29)
    at new Promise (<anonymous>)
    at FTPContext.handle (/Users/patrick/Documents/Projects/basic-ftp/lib/FtpContext.js:267:16)
    at Client.send (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:98:25)
    at enterPassiveModeIPv6 (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:656:30)
    at Client.autoDetect [as prepareTransfer] (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:631:35)
    at Client.list (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:347:20)
    at example (/Users/patrick/Documents/Projects/basic-ftp/temp/example.js:36:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Caused by: Error: User launched a task while another one is still running. Forgot to use 'await' or '.then()'?
    at FTPContext.handle (/Users/patrick/Documents/Projects/basic-ftp/lib/FtpContext.js:263:25)
    at Client.send (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:98:25)
    at enterPassiveModeIPv6 (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:656:30)
    at Client.autoDetect [as prepareTransfer] (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:631:35)
    at Client.list (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:347:20)
    at example (/Users/patrick/Documents/Projects/basic-ftp/temp/example.js:36:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Running task launched at: Error
    at Promise (/Users/patrick/Documents/Projects/basic-ftp/lib/FtpContext.js:279:24)
    at new Promise (<anonymous>)
    at FTPContext.handle (/Users/patrick/Documents/Projects/basic-ftp/lib/FtpContext.js:267:16)
    at Client.send (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:98:25)
    at enterPassiveModeIPv6 (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:656:30)
    at Client.autoDetect [as prepareTransfer] (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:631:35)
    at Client.list (/Users/patrick/Documents/Projects/basic-ftp/lib/ftp.js:347:20)
    at example (/Users/patrick/Documents/Projects/basic-ftp/temp/example.js:35:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by patrickjuchli** [comment]
There will still be a second exception which is probably uncaught by the user. I don't know how to get rid of that one. But this feature is a help during development, so it's not that terrible.

**Comment by patrickjuchli** [comment]
Improved in 3.0.0
