### ISSUE TITLE
source.pipe is not a function

### ISSUE THREAD

**Issue by joneldiablo** [patrickjuchli/basic-ftp#66]
has this error await ftp.upload......
TypeError: source.pipe is not a function
Client.js:764
    at onConditionOrEvent (/home/diablo/dev/bquate/repos/coda-pbb/node_modules/basic-ftp/dist/Client.js:764:24)
    at onConditionOrEvent (/home/diablo/dev/bquate/repos/coda-pbb/node_modules/basic-ftp/dist/Client.js:831:9)
    at Object.ftp.handle [as responseHandler] (/home/diablo/dev/bquate/repos/coda-pbb/node_modules/basic-ftp/dist/Client.js:761:13)
    at FTPContext.passToHandler (/home/diablo/dev/bquate/repos/coda-pbb/node_modules/basic-ftp/dist/FtpContext.js:247:23)
    at FTPContext.onControlSocketData (/home/diablo/dev/bquate/repos/coda-pbb/node_modules/basic-ftp/dist/FtpContext.js:238:18)
    at Socket.socket.on.data (/home/diablo/dev/bquate/repos/coda-pbb/node_modules/basic-ftp/dist/FtpContext.js:110:44)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)

**Comment by patrickjuchli** [comment]
Are you providing maybe a string instead of a readable stream to `ftp.upload`? See https://github.com/patrickjuchli/basic-ftp/#introduction for an example how to upload.

In the future, please provide a complete example of what you do. "await ftp.upload doesn't work" doesn't provide enough information for me to help you.

**Comment by joneldiablo** [comment]
ok, thank you. sorry, we have use fs.readFileSync instead fs.createReadStream

**Comment by rakeshnambiar** [comment]
hi, @patrickjuchli appreciate your effort. I tried to copy a `tar.gz` file and end up with the same error. Does this only support the readable stream?
